<html>
<head>
<title><?php echo $_GET['q'] ?> - Dr. Google Diagnosis</title>
<meta http-equiv="content-type" content="text/html;charset=UTF-8">
<style>.header td{border-top:1px solid #36c;padding-right:4px}body,td,div,.p,a{font-family:arial,sans-serif}#pagetitle{font-size:larger}#navlinks{font-size:smaller}#source,input#url{width:100%}form{padding-bottom:0;margin-bottom:0;padding-top:0;margin-top:0}#source{height:100%;overflow:auto}option.line-above{border-top:#ddd solid 1px;margin-top:-1px}table#texttable,table#webtable,table#suggesttable{width:100%}h4{background:#e5ecf9;padding:.2em;margin-top:1em;margin-bottom:.5em;padding-left:.5em;padding-right:.5em}#texttable table{padding:0;margin:0}#texttable table td{padding:0;margin:0}#texttable #submitcell select{padding:0;margin:0}#texttable #submitcell table{width:100%}#selectcell{width:100%}#result_box,#source{font:10pt monospace}.almost_half_cell{width:49%}#gap{width:2%;height:128px}#original_text,#autotrans{font-size:smaller}.highlight{background:#f5f5f5}.footer{border-top:1px solid #ccc;padding-top:1em;margin-top:2.5em;text-align:center;font-size:smaller}select{font-family:arial unicode ms,arial,sans-serif}#gbar{float:left;height:22px}.gbh,.gbd{border-top:1px solid #c9d7f1;font-size:1px}.gbh{height:0;position:absolute;top:24px;width:100%}#gbs,.gbm{background:#fff;left:0;position:absolute;text-align:left;visibility:hidden;z-index:1000}.gbm{border:1px solid;border-color:#c9d7f1 #36c #36c #a2bae7;z-index:1001}#guser{padding-bottom:7px !important;text-align:right}#gbar,#guser{font-size:13px;padding-top:1px !important}.gb1{margin-right:.5em}.gb1,.gb3{zoom:1}.gb2{display:block;padding:.2em .5em}.gb2,.gb3{text-decoration:none}a.gb1,a.gb2,a.gb3,a.gb4{color:#00c !important}a.gb2:hover{background:#36c;color:#fff !important}</style>
<style>body{background:#fff;color:#000;margin:3px 8px}#gbar{float:left;height:22px}.gbh,.gbd{border-top:1px solid #c9d7f1;font-size:1px}.gbh{height:0;position:absolute;top:24px;width:100%}#gbs,.gbm{background:#fff;left:0;position:absolute;text-align:left;visibility:hidden;z-index:1000}.gbm{border:1px solid;border-color:#c9d7f1 #36c #36c #a2bae7;z-index:1001}#guser{padding-bottom:7px !important;text-align:right}#gbar,#guser{font-size:13px;padding-top:1px !important}.gb1{margin-right:.5em}.gb1,.gb3{zoom:1}.gb2{display:block;padding:.2em .5em}.gb2,.gb3{text-decoration:none}a.gb1,a.gb2,a.gb3,a.gb4{color:#00c !important}a.gb2:hover{background:#36c;color:#fff !important}a.gb1,a.gb2,a.gb3,.link{color:#20c!important}.ts{border-collapse:collapse}.ts td{padding:0}.ti,.bl,form,#res h3{display:inline}.ti{display:inline-table}.fl:link,.gl,.gl a:link{color:#77c}a:link,.w,#prs a:visited,#prs a:active,.q:active,.q:visited{color:#20c}.mblink:visited,a:visited{color:#551a8b}a:active{color:red}.cur{color:#a90a08;font-weight:bold}.b{font-weight:bold}.j{width:42em;font-size:82%}.s{max-width:42em}.sl{font-size:82%}#gb{text-align:right;padding:1px 0 7px;margin:0}.hd{position:absolute;width:1px;height:1px;top:-1000em;overflow:hidden}.f,.m,.c h2,#mbEnd h2{color:#676767}.a,cite,.cite,.cite:link{color:green;font-style:normal}#mbEnd{float:right}h1,ol{margin:0;padding:0}li.g,body,html,.std,.c h2,#mbEnd h2,h1{font-size:small;font-family:arial,sans-serif}.c h2,#mbEnd h2,h1{font-weight:normal}#ssb,.clr{clear:both;margin:0 8px}#nav a,#nav a:visited,.blk a{color:#000}#nav a{display:block}#nav .b a,#nav .b a:visited{color:#20c}#nav .i{color:#a90a08;font-weight:bold}.csb,.ss,#logo span,#rptglbl{background:url(/images/nav_logo7.png) no-repeat;overflow:hidden}.csb,.ss{background-position:0 0;height:26px;display:block}.ss{background-position:0 -88px;position:absolute;left:0;top:0}.cps{height:18px;overflow:hidden;width:114px}.mbi{width:13px;height:13px;background-position:-91px -74px;position:relative;top:2px;margin-right:3px}#nav td{padding:0;text-align:center}#logo{display:block;overflow:hidden;position:relative;width:103px;height:37px;margin:11px 0 7px}#logo img{border:none;position:absolute;left:-0px;top:-26px}.w10,.w11,.w20,.w21,.w24,.wci,.wpb,.w4,.w5,.w40,.w41,.w44,.w50,.w51,.w54,li.w0 .w5,li.w1 .w5{background:url(/images/nav_logo7.png) no-repeat;border:0;cursor:pointer;display:none;margin-right:3px;height:14px;vertical-align:bottom;width:14px}.w10,.w11,.w20,.w21,.w24{height:16px;margin-left:8px;width:16px}.w10{background-position:-104px -42px}.w11{background-position:-134px -27px;cursor:default;display:inline}.w20{background-position:-104px -57px}.w21{background-position:-104px -27px}.w24{background-position:-134px -44px;cursor:default;display:inline}.wci,.w4,.w5,.w40,.w41,.w44,.w50,.w51,.w54,li.w0 .w5,li.w1 .w5{display:inline;height:14px;width:14px}
.w14,.w44,.w54{display:none}
.wci{background-position:-119px -87px;height:14px;width:16px}.wpb{background-position:-91px -74px;display:inline;height:13px;vertical-align:5px;width:13px}.w4,.w40,.w41,.w44{background-position:-104px -42px}.w5,.w50,li.w0 .w5,.w54{background-position:-104px -57px}.w51,li.w1 .w5{background-position:-104px -27px}.wcd{margin-top:2px;max-width:42em}button::-moz-focus-inner{border:0}.link{color:#00c;text-decoration:underline;cursor:pointer}.link:active{color:red}.pin{overflow:hidden;height:36px;width:22px;position:relative;display:block}.pin img{position:absolute}.pin1{top:0}.pin2{top:-36px}.pin3{top:-72px}.pin4{top:-108px}.pin5{top:-144px}.pin6{top:-180px}.pin7{top:-216px}.pindot{bottom:0px}#logo span,.ch{cursor:pointer}.lst{font-family:arial,sans-serif;font-size:17px;vertical-align:middle}.lsb{font-family:arial,sans-serif;font-size:15px;height:1.85em;vertical-align:middle}h3,.med{font-size:medium;font-weight:normal;padding:0;margin:0}.e{margin:.75em 0}.bc a{color:green;text-decoration:none}.bc a:hover{text-decoration:underline}
.slk td{padding-left:40px;padding-top:5px;vertical-align:top}.slk div{padding-left:10px;text-indent:-10px}.fc{margin-top:.5em;padding-left:3em}#mbEnd cite{display:block;text-align:left}#mbEnd p{margin:-.5em 0 0 .5em;text-align:center}#bsf,#ssb,.blk{border-top:1px solid #6b90da;background:#f0f7f9}#bsf{border-bottom:1px solid #6b90da}#flp{margin:7px 0}#ssb div{float:left;padding:4px 0 0;padding-left:7px;padding-right:.5em}#prs a,#prs b{margin-right:.6em}#ssb p{text-align:right;white-space:nowrap;margin:.1em 0;padding:.2em}#ssb{margin:0 8px 11px;padding:.1em}#cnt{max-width:80em;clear:both}#mbEnd{background:#fff;padding:0;border-left:11px solid #fff;border-spacing:0;white-space:nowrap}#res{padding-right:1em;margin:0 16px}.c{background:#fff8dd;margin:0 8px}.c li{padding:0 3px 0 8px;margin:0}.c .tam,.c .tal{padding-top:12px}#mbEnd li{margin:1em 0;padding:0}.xsm{font-size:x-small}.sm{margin:0 0 0 40px;padding:0}ol li{list-style:none}.sm li{margin:0}.gl,#bsf a,.nobr{white-space:nowrap}#mbEnd .med{white-space:normal}.sl,.r{display:inline;font-weight:normal;margin:0}.r{font-size:medium}h4.r{font-size:small}.mr{margin-top:-.5em}.rt1 {background:transparent url(/images/bubble1.png) no-repeat;}.rt2 {background:transparent url(/images/bubble2.png) repeat 0 0 scroll;}.sb {background: url(/images/scrollbar.png) repeat scroll 0 0;cursor:pointer;width:14px;}.rtdm:hover {text-decoration:underline;}.ri_cb{left:0;margin:6px;position:absolute;top:0;z-index:1}.ri_sp{display:-moz-inline-box;display:inline-block;text-align:center;vertical-align:top;margin-bottom:6px}.ri_sp img{vertical-align:bottom}.g{margin:1em 0}.mbl{margin:1em 0 0}em{font-weight:bold;font-style:normal}.tbi div, #tbp{background:url(/images/nav_logo7.png) no-repeat;overflow:hidden;width:13px;height:13px;}#ssb #tbp{background-position:-91px -74px;padding:0;margin-top:1px;margin-left:0.75em;}.tbpo,.tbpc{margin-left:3px;margin-right:1em;text-decoration:underline;white-space:nowrap;}.tbpc,.tbo .tbpo {display:inline}.tbo .tbpc,.tbpo{display:none}#prs *{float:left}#prs a, #prs b{margin-right:.3em}.std dfn{padding-left:.2em;padding-right:.5em}dfn{font-style:normal;font-weight:bold;padding-left:1px;position:relative;top:-.12em}#tbd{display:none;margin-left:-9.6em;z-index:1}.tbo #tads,.tbo #pp,.tbo #tadsb{margin-left:13em}.tbo #res{margin-left:11.05em;}.tbo #tbd{width:9.6em;padding:0;left:11px;background:#fff;border-right:1px solid #c9d7f1;position:absolute;display:block;margin-left:0}.tbo #mbEnd{width:26%}</style>
<noscript>
<style>#clirb{display:none}</style>
</noscript>
<script>
window.google={kEI:"reZmS4solbqyBtbc6dQD",kEXPI:"17259,21678,23351,23388,52142",kCSI:{e:"17259,21678,23351,23388,52142",ei:"reZmS4solbqyBtbc6dQD",expi:"17259,21678,23351,23388,52142"},kHL:"en",time:function(){return(new Date).getTime()},log:function(b,d,c){var a=new Image,e=google,g=e.lc,f=e.li;a.onerror=(a.onload=(a.onabort=function(){delete g[f]}));g[f]=a;c=c||"<?php echo BASE_PATH; ?>gen_204?atyp=i&ct="+b+"&cad="+d+"&zx="+google.time();a.src=c;e.li=f+1},lc:[],li:0,Toolbelt:{}};
google.y={};google.x=function(e,g){google.y[e.id]=[e,g];return false};(function(){if(!window.google)window.google={};window.google.translate={};window.google.translate.sfp = function(f){if(encodeURIComponent(f.text.value).length<1800){f.method='get'}else{f.method='post'}}})();window.gbar={};(function(){var e=window.gbar,g,j;function k(a){var b=window.encodeURIComponent&&(document.forms[0].q||"").value;if(b)a.href=a.href.replace(/([?&])q=[^&]*|$/,function(h,d){return(d||"&")+"q="+encodeURIComponent(b)})}e.qs=k;function m(a,b,h,d,f,l){var i=document.getElementById(a),c=i.style;if(i){c.left=d?"auto":b+"px";c.right=d?b+"px":"auto";c.top=h+"px";c.visibility=j?"hidden":"visible";if(f){c.width=f+"px";c.height=l+"px"}else{m(g,b,h,d,i.offsetWidth,i.offsetHeight);j=j?"":a}}}e.tg=function(a){a=a||window.event;var b=a.target||a.srcElement;a.cancelBubble=true;if(!g){a=document.createElement(Array.every||window.createPopup?"iframe":"div");a.frameBorder="0";a.src="#";g=b.parentNode.appendChild(a).id="gbs";document.onclick=e.close;if(e.alld){e.alld(function(){n(b)});return}}n(b)};function n(a){var b=0,h,d=window.navExtra;if(a.className!="gb3")a=a.parentNode;var f=a.getAttribute("aria-owns")||"gbi",l=a.offsetWidth,i=a.offsetTop>20?46:24,c;do b+=a.offsetLeft||0;while(a=a.offsetParent);if(f=="gbi")for(a=document.getElementById(f);d&&(h=d.pop());)a.insertBefore(h,a.firstChild).className="gb2";else c=b=(document.documentElement.clientWidth||document.body.clientWidth)-b-l;j!=f&&e.close();m(f,b,i,c)}e.close=function(){j&&m(j,0,0)}})();</script>
</head>
<body alink=#ff0000 bgcolor=#ffffff link=#0000cc vlink=#551a8b topmargin=3 marginheight=3>

<div id=gbar>
 <nobr>
 <b class=gb1>Web</b> <a href="http://images.google.com/imghp?hl=en&tab=wi" onclick=gbar.qs(this) class=gb1>Images</a> <a href="http://video.google.com/?hl=en&tab=wv" onclick=gbar.qs(this) class=gb1>Videos</a> <a href="http://maps.google.com/maps?hl=en&tab=wl" onclick=gbar.qs(this) class=gb1>Maps</a> <a href="http://news.google.com/nwshp?hl=en&tab=wn" onclick=gbar.qs(this) class=gb1>News</a> <a href="http://www.google.com/prdhp?hl=en&tab=wf" onclick=gbar.qs(this) class=gb1>Shopping</a> <a href="http://mail.google.com/mail/?hl=en&tab=wm" class=gb1>Mail</a> <a href="http://www.google.com/intl/en/options/" onclick="this.blur();gbar.tg(event);return !1" aria-haspopup=true class=gb3><u>more</u> <small>&#9660;</small></a>
 <div class=gbm id=gbi>
  <a href="http://books.google.com/bkshp?hl=en&tab=wp" onclick=gbar.qs(this) class=gb2>Books</a> <a href="http://www.google.com/finance?hl=en&tab=we" onclick=gbar.qs(this) class=gb2>Finance</a> <a href="http://translate.google.com/?hl=en&tab=wT" onclick=gbar.qs(this) class=gb2>Translate</a> <a href="http://scholar.google.com/schhp?hl=en&tab=ws" onclick=gbar.qs(this) class=gb2>Scholar</a> <a href="http://blogsearch.google.com/?hl=en&tab=wb" onclick=gbar.qs(this) class=gb2>Blogs</a>
  <div class=gb2><div class=gbd></div></div>
  <a href="http://www.youtube.com/?hl=en&tab=w1" onclick=gbar.qs(this) class=gb2>YouTube</a> <a href="http://www.google.com/calendar/render?hl=en&tab=wc" class=gb2>Calendar</a> <a href="http://picasaweb.google.com/home?hl=en&tab=wq" onclick=gbar.qs(this) class=gb2>Photos</a> <a href="http://docs.google.com/?hl=en&tab=wo" class=gb2>Documents</a> <a href="http://www.google.com/reader/view/?hl=en&tab=wy" class=gb2>Reader</a> <a href="http://sites.google.com/?hl=en&tab=w3" class=gb2>Sites</a> <a href="http://groups.google.com/grphp?hl=en&tab=wg" onclick=gbar.qs(this) class=gb2>Groups</a>
  <div class=gb2><div class=gbd></div></div>
  <a href="http://www.google.com/intl/en/options/" class=gb2>even more &raquo;</a>
 </div>
 </nobr>
</div>

<div id=guser width=100%>
 <nobr>
 <a href="http://www.fffff.at/">iGoogle</a> | <a href="http://www.fffff.at/chat">Sign in</a>
 </nobr>
</div>
<div class=gbh style=left:0></div>
<div class=gbh style=right:0></div>
<table border=0 cellpadding=0 cellspacing=0 style="clear:both" width=100%>
 <tr>
  <td valign=top width=1%><a href="<?php echo BASE_PATH; ?>"><img alt=Google src="<?php echo BASE_PATH; ?>images/logo_sm.gif" border=0 height=55 width=174></a></td>
  <td>&nbsp;</td>
  <td nowrap>
   <table border=0 cellpadding=0 cellspacing=0 width=100% class=header>
    <tr>
     <td bgcolor=#e5ecf9 nowrap><font size=+1><b>&nbsp;Diagnosis for <?php echo $_GET['q']; ?></b></font></td>
     <td align=right bgcolor=#e5ecf9 nowrap><font face=arial,sans-serif size=-1><a href="http://www.fffff.at/introducing-dr-google">About Dr. Google</a></font></td>
    </tr>
   </table>
  </td>
 </tr>
</table>
<p></p>
<div style="max-width: 1020px">
<h4><font size="+1"><?php echo $diagnosis['title']; ?></font></h4>
<div style="padding: 0 0 0 4px;">
<?php echo pretty_format($diagnosis['text']); ?>
</div>


<div style="height:1px;line-height:0"></div><div style="text-align:center;margin-top:1.4em" class=clr><div id=bsf style="padding:1.8em 0;margin-top:0"><form method=get action="<?php echo BASE_PATH; ?>search"><div><input class=lst type=text name=q size=41 maxlength=2048 value="<?php echo $_GET['q']; ?>" title="Search"> <input type=submit name="btnI" class=lsb style="margin:0 2px 0 5px" value="Search"><input type=hidden name=hl value="en"><input type=hidden name=safe value="off"><input type=hidden name=sa value="2"></div></form><p style="margin:1.2em 0 0"></div><p id=flp><a href="http://www.fffff.at/">Google&nbsp;Home</a> - <a href="http://www.fffff.at/contact">Advertising&nbsp;Programs</a> - <a href="http://www.fffff.at/people">Business Solutions</a> - <a href="http://www.fffff.at">Privacy</a> - <a href="http://www.fffff.at">About Google</a></p></div>
</div>
<font size=-1><center><p><s>&copy;2010</s> Dr. Google</center></font>
</body>
</html>